import {
  ArrowRight,
  BookOpen,
  BookOpenText,
  Bookmark,
  Clock3,
  ExternalLink,
  GitFork,
  Globe2,
  Layers3,
  ListFilter,
  Moon,
  Play,
  Plus,
  RefreshCw,
  Rss,
  Settings,
  Sparkles,
  Star,
  Sun,
  Terminal,
  Trash2,
  Triangle,
} from '@lucide/vue';
import GithubBrandIcon from './GithubBrandIcon.vue';
import GoogleBrandIcon from './GoogleBrandIcon.vue';

export const iconRegistry = {
  arrow: ArrowRight,
  book: BookOpen,
  bookmark: Bookmark,
  clock: Clock3,
  external: ExternalLink,
  filter: ListFilter,
  fork: GitFork,
  github: GithubBrandIcon,
  globe: Globe2,
  google: GoogleBrandIcon,
  layers: Layers3,
  moon: Moon,
  play: Play,
  plus: Plus,
  refresh: RefreshCw,
  repo: BookOpenText,
  rss: Rss,
  settings: Settings,
  sparkles: Sparkles,
  star: Star,
  sun: Sun,
  terminal: Terminal,
  trash: Trash2,
  triangle: Triangle,
} as const;

export type IconName = keyof typeof iconRegistry;
